### ISSUE TITLE
Trying to add Mods and a custom map

### ISSUE THREAD

**Issue by BJET67** [RouHim/beammp-container-image#40]
I'm new to docker but I got the standard docker version (not compose) running and everything works perfect but I'm stuck trying to add a map to this server and some mods also. Where would I even start?

**Comment by RouHim** [comment]
Hey BJET67,
I don't want to come across as nasty, but this is not a docker support forum. If you have a specific question about the beammp server please post here, otherwise I can also recommend the docker forum, the people there are very friendly: https://forums.docker.com/c/general-discussions/23

I would like to help you, but I just don't have the time.

**Comment by BJET67** [comment]
cool

**Comment by konstkarapan** [comment]
> cool

did you manage to make it work? Im struggling as well
