### ISSUE TITLE
Mod folders suddenly empty

### ISSUE THREAD

**Issue by pedder55655** [RouHim/beammp-container-image#61]
Hi,

I'm not sure where to put it but with the recent update my mods didn't work anymore.

Took my several hours to figure out what was wrong.
Im using Docker-Compose, and I've mapped a host folder called /data/beammp/Resources as volume under /beammp/Resources. But you've created 2 volumes now underneath that folder (see https://github.com/RouHim/beammp-container-image/blob/dc4685903d11b4b32feaf1ddd08001404b5547d0/Containerfile#L53).

That automatically creates empty Docker volumes and I couldn't figure out why my mod folders were suddenly empty. As I said, It took me several hours to find that out.  I've mapped those 2 folders Resources/Client & Server individually now and it correctly supersedes your volumes from the Containerfile. 

I thought, I'd mention that. Maybe its something you wanna add to the "Breaking Change" section of the readme.

Anyhow, thanks for your efforts maintaining this.

**Comment by RouHim** [comment]
Hi thanks for your report.

I don't want to sound harsh, because I know how complex and annoying it is to debug such errors, but in the documentation of the container image these two folders have always been mounted separately. That's why I only have the documented things in my head when I make changes.

Still bad that you lost data because of this, sorry.

**Comment by pedder55655** [comment]
It's alright, no data was lost. Just some of my time. The data re-appeared after I've mounted the two separate volumes. Cheers :)
